"""

    Problem 12:

    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?

"""

import time

def get_factors(number):
    factor_list = []

    i = 1

    while i*i <= number:
        if number%i == 0:
            factor_list.append(i)

            if number//i != i:
                factor_list.append(number//i)

        i = i + 1

    return factor_list

if __name__ == "__main__":
    starting_time = time.time()

    triangular_number = 0
    x = 0

    while True:
        x = x + 1
        triangular_number = triangular_number + x

        if triangular_number%2 == 0:
            if len(get_factors(triangular_number)) > 500:
                break

    print(triangular_number)

    print("\nExecution time: ", float(time.time() - starting_time), " seconds")